# 1. Creating Arrays

**Q1**: How do you create a NumPy array from a list `[1, 2, 3, 4]`?

**Q2**: How can you create a 2x3 array filled with zeros?

**Q3**: Write a NumPy command to create an array of integers from 10 to 20.


In [79]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

arr_z = np.zeros((2,3))
print(arr_z)

arr_r = np.arange(10,20)
print(arr_r)

[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]
[10 11 12 13 14 15 16 17 18 19]
[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]
[10 11 12 13 14 15 16 17 18 19]


# 2. Array Indexing and Slicing

**Q4**: How do you access the element at the second row and third column of the following array?

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [80]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1,2])

6


**Q5**: How can you extract the first two rows and the last two columns from the array below?

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [81]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[:2]) # first two columns
print(arr[0:3, 1:3]) # last two columns

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]


**Q6**: How do you reverse the array `[1, 2, 3, 4, 5]` using slicing?


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[::-1])

# 3. Array Operations

**Q7**: Given two arrays `a = np.array([1, 2, 3])` and `b = np.array([4, 5, 6])`, how do you perform element-wise addition?

**Q8**: How do you multiply each element of an array by a scalar value (e.g., multiply all elements by 5)?


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a + b
print(c)

d = a * 5
print(d)

Q9: Write a command to compute the dot product of two arrays:


In [ ]:
x = a @ b
print(x)

# 4. Array Shape and Reshaping

**Q10**: How can you check the shape (dimensions) of an array?

**Q11**: Convert a 1D array with 12 elements into a 2D array with 3 rows and 4 columns.

**Q12**: What happens if you try to reshape an array to an incompatible shape?


In [ ]:
print(a.shape)
print(a.ndim)

a = np.arange(12)
print(a.reshape(3,4))

#print(a.reshape(4,4)) this returns Error:cannot reshape to size(4,4)

# 5. Array Statistics

**Q13**: How do you calculate the mean of all elements in an array?

**Q14**: How can you find the maximum value in an array?

**Q15**: Write a NumPy command to calculate the sum of each column in a 2D array.


In [ ]:
# a = [ 0  1  2  3  4  5  6  7  8  9 10 11]

print(np.mean(a))

print(sum(a)/len(a))

print(np.max(a))

c = np.arange(1,17).reshape(4,4)
print(c.ndim)

print(c)
# Sum along columns
col_sum = np.sum(c, axis=0)
print(col_sum)

# Sum along rows
row_sum = np.sum(c, axis=1)
print(row_sum)

# here axis is the factor that decides wether to sum along col or rows. here axis 0 is for col.

# 6. Random Numbers and Arrays

**Q16**: How do you generate a 1D array of 5 random numbers between 0 and 1?

**Q17**: How do you create a 3x3 matrix with random integers between 1 and 10?

**Q18**: Write a command to set the seed for NumPy's random number generator to ensure reproducibility.


In [ ]:
a = np.random.random(5)
print(a)

b = np.random.randint(0, 2, 5, dtype=np.int64)
print(b)

c = np.random.randint(1, 11, (3,3), dtype=np.int64)
print(c)

# On setting a seed value you ensure that the random numbers generated each time code is run will remain same.

np.random.seed(10)

d = np.random.rand(5)
# [0.77132064 0.02075195 0.63364823 0.74880388 0.49850701] - this will be the sequence.
e = np.random.rand(5)
# [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
print(d)
print(e)

# 7. Boolean Indexing and Filtering

**Q19**: Given an array `arr = np.array([10, 20, 30, 40, 50])`, how do you filter the elements that are greater than 25?

**Q20**: How do you replace all negative values in an array with zero?

**Q21**: How can you count the number of elements in an array that are greater than a specified value?


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
filtered_elements = arr[arr > 25]
print(filtered_elements) 

arr = np.array([-5, 3, -2, 8, -1])
arr[arr < 0] = 0
print(arr)

# counted the number of elements greater that 0 in arr
print(len(arr[arr>0]))

# or

print(np.sum(arr>0))

# 8. Array Concatenation and Splitting

**Q22**: How do you concatenate two arrays `a = np.array([1, 2, 3])` and `b = np.array([4, 5, 6])`?

**Q23**: Write a command to split a 1D array of 10 elements into 5 equal-sized arrays.

**Q24**: How can you horizontally stack two 2D arrays?


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
 
c = np.concatenate((a,b))
print(c)

d = np.arange(1,11)
print(np.array_split(d, 5))

a_1 = np.array([[1, 2], [3, 4]])
a_2 = np.array([[5, 6], [7, 8]])
for row1, row2 in zip(a_1, a_2):
    print(f"{row1}  {row2}")

# Horizontally stack the two arrays
h_stack = np.hstack((a_1, a_2))
print(h_stack)

# Vertically stack two arrays
v_stack = np.vstack((a_1, a_2))
print(v_stack)

# 9. Array Broadcasting

**Q25**: What is broadcasting in NumPy, and how does it work with the following example?

```python
import numpy as np

a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])
result = a + b
print(result)


**Broadcasting** in NumPy is a technique that allows operations between arrays of different shapes. It automatically expands the smaller array to match the shape of the larger array for element-wise operations.

Given the arrays:

```python
import numpy as np

a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])
result = a + b
print(result)

```

Here, a is a 2D array with shape (3, 1) and b is a 1D array with shape (3,).

When performing any kind of operation between these two arrays, the smaller array, i.e., b, will be broadcast onto a.

For example, in the operation a + b:

The value 1 in a will be added to all columns of b, resulting in [5, 6, 7].
The value 2 in a will be added to all columns of b, resulting in [6, 7, 8].
The value 3 in a will be added to all columns of b, resulting in [7, 8, 9].

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])
result = a + b
print(result)

# 10. Array Copying

**Q26**: What is the difference between a shallow copy and a deep copy in NumPy?

**Q27**: How do you create a deep copy of an array in NumPy?

**Q28**: How do you modify an array without changing the original array?


In [ ]:
# Array copies are not created by simple assignment operator.
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a            # no new object is created
print(b is a)    # a and b are two names for the same ndarray object

# View or shallow Copy
# different array objects can share the same data. we use view method to create new objecct sharing the same data.
c = a.view()
c is a
# False
c.base is a            # c is a view of the data owned by a
# True
c.flags.owndata
# False

c = c.reshape((2, 6))  # a's shape doesn't change
a.shape
# (3, 4)
c[0, 4] = 1234         # a's data changes
a
# array([[   0,    1,    2,    3],
#        [1234,    5,    6,    7],
#        [   8,    9,   10,   11]])

# Deep Copy
d = a.copy()  # a new array object with new data is created
print(d is a)
print(d.base is a)  # d doesn't share anything with a
d[0, 0] = 9999
print(a)
print(d)

### 11. Vectorization in NumPy

Vectorization in NumPy refers to the ability to perform operations on entire arrays or large chunks of data at once, without the need for explicit loops in Python. This is achieved by leveraging highly optimized C and Fortran code that NumPy uses internally, which leads to significant performance improvements.

#### Key Points of Vectorization:

1. **Performance**: Vectorized operations are much faster than equivalent operations performed using explicit Python loops. This is because the operations are executed in compiled code rather than interpreted Python code.

2. **Conciseness**: Code that uses vectorized operations is often more concise and readable. You can perform operations on entire arrays with a single line of code.

3. **Memory Efficiency**: Vectorized operations avoid the overhead of Python loops and make use of optimized low-level implementations, which can also lead to better memory usage.

#### Example of Vectorization:

**Without Vectorization (Using a Loop):**

```python
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Element-wise addition using a loop
result = np.zeros_like(a)
for i in range(len(a)):
    result[i] = a[i] + b[i]

```
** With Vectorization:**

```python
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Element-wise addition using vectorization
result = a + b
```
In the vectorized version, the addition operation is applied to all elements of arrays a and b in one go. This is not only more efficient but also results in cleaner and more readable code.

Common Vectorized Operations:
Arithmetic Operations: +, -, *, / are performed element-wise.

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  # Result: [5, 7, 9]
```
Mathematical Functions: Functions like np.sin, np.exp, np.log are applied element-wise.

```python
a = np.array([0, np.pi/2, np.pi])
b = np.sin(a)  # Result: [0.0, 1.0, 0.0]
```
Logical Operations: Operations like &, |, ~ are used for element-wise logical operations.

```python
a = np.array([True, False, True])
b = np.array([False, False, True])
c = a & b  # Result: [False, False, True]
```
Aggregation: Operations like np.sum, np.mean, np.max can be used to perform reductions.

```python
a = np.array([1, 2, 3, 4])
total = np.sum(a)  # Result: 10


**Broadcasting:**
Vectorization also involves a concept called broadcasting, which allows NumPy to perform operations on arrays of different shapes in a way that makes them compatible. This can be seen as a form of vectorization that deals with arrays of differing sizes