# Tensor Flow

TensorFlow is a powerful open-source machine-learning framework developed by Google, that empowers developers to construct and train ML model.

**TensorFlow** is basically a software library for numerical computation using **data flow graphs** where:

*   **nodes** in the graph represent mathematical operations.
    
*   **edges** in the graph represent the multidimensional data arrays (called **tensors**) communicated between them. (Please note that **tensor** is the central unit of data in TensorFlow).

![](https://media.geeksforgeeks.org/wp-content/uploads/graph1.png)

Here, add = Node, a and b are input tensors and c is resultant tensor.

### Tensors
Tensors are the primary data sructure in Tensorflow.They are multi-dimensional arrays. we can create them by **tf.constants** or **tf.variables.**

#### Tensor Operations
**1. Addition :**
 use tf.add()

In [1]:
import tensorflow as tf
import numpy

# Ensure eager execution is enabled
tf.config.run_functions_eagerly(True)

# Creating tensors
node1 = tf.constant(3, dtype=tf.int32)
node2 = tf.constant(5, dtype=tf.int32)

# Performing addition
node3 = tf.add(node1, node2)

# Evaluating and printing the result
print("Sum of node1 and node2 is:", node3.numpy())


Sum of node1 and node2 is: 8


TensorFlow 2.x, by default, runs in eager execution mode, which means operations are executed immediately as they are defined. However, when using tf.compat.v1.Session(), it attempts to use the graph-based execution model from TensorFlow 1.x, and that's why we have used disable_eager_execution here.

Node 1 and node 2 are constant type nodes, and df_type defines autput value.
Node3 is of tf.add type. It takes two tensors as input and returns their sum as output tensor.

**Variables**
-------------

TensorFlow has **Variable** nodes too which can hold variable data. They are mainly used to hold and update parameters of a training model. Variables are **in-memory buffers** containing tensors. They must be explicitly initialized and can be saved to disk during and after training. You can later restore saved values to exercise or analyze the model. An important difference to note between a **constant** and **Variable** is:

> A constant’s value is stored in the graph and its value is replicated wherever the graph is loaded. A variable is stored separately, and may live on a parameter server.

**Note:** There is no need for tf.Session() in 2.x, Eager execution allows operations to be evaluated immediately as they are defined, eliminating the need for sessions and graphs as used in TensorFlow 1.x.

In [2]:
import tensorflow as tf

# create a variable
node = tf.Variable(tf.zeros([2, 2]))

# TensorFlow 2.x automatically initializes variables
# You can directly evaluate the variable
#To assign a new value to a variable node, we can use assign method like this:
node = node.assign(node + tf.ones([2,2]))

print("Evaluating node:\n", node.numpy())


Evaluating node:
 [[1. 1.]
 [1. 1.]]


##### Matrix Multiplication
![](https://media.geeksforgeeks.org/wp-content/uploads/placeholder2.png)

In [3]:

# Define the input tensors
a = tf.constant([[1], [2], [3]], dtype=tf.int32)  # Example input
b = tf.constant([[4, 5, 6]], dtype=tf.int32)      # Example input

# Perform matrix multiplication
c = tf.matmul(a, b)

# Print the result
print("Result of matrix multiplication:\n", c.numpy())


Result of matrix multiplication:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [4]:
# all tensor opertaions
tensor_a = tf.constant([1, 2, 3, 4], dtype=tf.float32)
tensor_b = tf.Variable([5, 6, 7, 8], dtype=tf.float32)

tensor_sum = tf.add(tensor_a, tensor_b)
tensor_prod = tf.multiply(tensor_a, tensor_b)
tensor_reshaped = tf.reshape(tensor_a, [2,2])
print("Eager Execution - Sum:", tensor_sum.numpy(), "\n",tensor_prod.numpy(), "\n", tensor_reshaped.numpy())


Eager Execution - Sum: [ 6.  8. 10. 12.] 
 [ 5. 12. 21. 32.] 
 [[1. 2.]
 [3. 4.]]


**Variables**

Variables are mutable and can be modified after creation.

In [5]:
variable_tensor = tf.Variable([1, 2, 3])
variable_tensor.assign([4, 5, 6])  # Update the value
print("Updated Variable:", variable_tensor.numpy())


Updated Variable: [4 5 6]


### **Simple Model Building**

### Building a model from scratch using TensorFlow's low-level API.

**Initialization (\_\_init\_\_ method)**:

*   self.dense1: Represents the first layer with 5 input features and 10 output neurons. It’s initialized with random normal values.
    
*   self.dense2: Represents the second layer with 10 input features and 1 output neuron.
    
*   **2.Forward Pass (\_\_call\_\_ method)**:
    
    *   **Matrix Multiplication**: tf.matmul(x, self.dense1) computes the dot product between input x and the weights of the first layer.
        
    *   **Activation Function**: tf.nn.relu(x) applies the ReLU activation function to introduce non-linearity.
        
    *   **Second Matrix Multiplication**: tf.matmul(x, self.dense2) computes the dot product between the output of the activation function and the weights of the second layer.

In [6]:
import tensorflow as tf

class SimpleModel(tf.Module):
    def __init__(self):
        # Initialize weights for two layers
        self.dense1 = tf.Variable(tf.random.normal([5, 10]), dtype=tf.float32)  # 5 input features, 10 neurons
        self.dense2 = tf.Variable(tf.random.normal([10, 1]), dtype=tf.float32)  # 10 neurons, 1 output feature

    def __call__(self, x):
        # Forward pass through the model
        x = tf.matmul(x, self.dense1)  # Matrix multiplication
        x = tf.nn.relu(x)             # ReLU activation
        x = tf.matmul(x, self.dense2) # Another matrix multiplication
        return x


Data preparation involves cleaning, transforming, and organizing data to ensure it’s suitable for training machine learning models. In TensorFlow, the tf.data API is a powerful tool for building efficient and flexible data pipelines, which can include operations like shuffling, batching, and preprocessing to optimize model training and evaluatio

In [7]:
import numpy as np

# Create synthetic data
x_data = np.random.random((100, 5)).astype(np.float32)
y_data = np.random.random((100, 1)).astype(np.float32)

# Create a TensorFlow dataset
dataset = tf.data.Dataset.from_tensor_slices((x_data, y_data))

# Shuffle and batch the dataset
dataset = dataset.shuffle(buffer_size=100).batch(10)

# Iterate through the dataset
for x_batch, y_batch in dataset:
    print("Batch of inputs:", x_batch.numpy())
    print("Batch of targets:", y_batch.numpy())

Batch of inputs: [[0.5022924  0.6090528  0.77783114 0.11015838 0.0831859 ]
 [0.3691568  0.30995917 0.65048194 0.81051886 0.00461418]
 [0.9505543  0.3746202  0.6093648  0.15278536 0.7194437 ]
 [0.02116243 0.9771841  0.19135043 0.42674702 0.20366372]
 [0.20307198 0.28119823 0.62064385 0.29586577 0.93047124]
 [0.95856524 0.18922615 0.443297   0.7555666  0.6294069 ]
 [0.96670544 0.29472393 0.77239954 0.09888712 0.40259075]
 [0.40480667 0.48696467 0.28061    0.8230132  0.18882361]
 [0.8776611  0.11563282 0.97182274 0.41684422 0.445032  ]
 [0.50174826 0.9802311  0.21975261 0.39084637 0.16310403]]
Batch of targets: [[0.99463874]
 [0.29450345]
 [0.6661221 ]
 [0.3298658 ]
 [0.55575186]
 [0.48880014]
 [0.20796114]
 [0.61132073]
 [0.09226964]
 [0.5103883 ]]
Batch of inputs: [[0.1915783  0.70247847 0.41826755 0.0471295  0.5455846 ]
 [0.6965107  0.10033588 0.6624184  0.4906634  0.84845334]
 [0.5164459  0.21045317 0.94720507 0.401826   0.19921386]
 [0.55765486 0.9271016  0.01121936 0.46941766 0.5646

#### Define Loss function and Optimizer
here we have implemented a loss function and an optimizer

In [8]:
def compute_loss(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))  # Mean Squared Error Loss

optimizer = tf.optimizers.Adam()  # Adam optimizer


**Training Loop**

Implement the training loop using TensorFlow’s tf.GradientTape to compute gradients and apply them to the model parameters:

In [9]:
# Initialize the model
model = SimpleModel()

# Training loop
epochs = 5
for epoch in range(epochs):
    epoch_loss = 0
    for x_batch, y_batch in dataset:
        with tf.GradientTape() as tape:
            y_pred = model(x_batch)  # Forward pass
            loss = compute_loss(y_batch, y_pred)  # Compute loss

        gradients = tape.gradient(loss, model.trainable_variables)  # Compute gradients
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))  # Apply gradients

        epoch_loss += loss.numpy()  # Accumulate loss

    print(f"Epoch {epoch + 1}, Loss: {epoch_loss / len(dataset)}")


Epoch 1, Loss: 0.3416737988591194
Epoch 2, Loss: 0.3071227766573429
Epoch 3, Loss: 0.2770118147134781
Epoch 4, Loss: 0.25374014526605604
Epoch 5, Loss: 0.23634570837020874


**5\. Evaluation**

To evaluate the model, use the test set (or the same dataset if no separate test set is available). The process is similar to training but without gradient updates:

In [10]:
# Evaluation
def evaluate_model(model, dataset):
    total_loss = 0
    num_batches = 0
    for x_batch, y_batch in dataset:
        y_pred = model(x_batch)  # Forward pass
        loss = compute_loss(y_batch, y_pred)  # Compute loss
        total_loss += loss.numpy()
        num_batches += 1

    average_loss = total_loss / num_batches
    return average_loss

# Evaluate the model on the same dataset (for demonstration purposes)
eval_loss = evaluate_model(model, dataset)
print(f"Evaluation Loss: {eval_loss}")


Evaluation Loss: 0.2256659597158432
